Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-08, with the labels that each got.

#215 Feature :: 학교 조회 및 급식 로직 구현
  src/main/kotlin/com/seugi/api/SeugiServerApplication.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/MealEntity.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/MealRepository.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/MealRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/MealRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/mapper/MealMapper.kt
  src/main/kotlin/com/seugi/api/domain/meal/domain/model/Meal.kt
  src/main/kotlin/com/seugi/api/domain/meal/exception/MealErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/meal/presentation/MealController.kt
  src/main/kotlin/com/seugi/api/domain/meal/service/MealService.kt
  src/main/kotlin/com/seugi/api/domain/meal/service/MealServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/entity/WorkspaceEntity.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/mapper/WorkspaceMapper.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/model/SchoolInfo.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/model/Workspace.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
  src/main/kotlin/com/seugi/api/global/config/FeignConfig.kt
  src/main/kotlin/com/seugi/api/global/exception/CommonErrorCode.kt
  src/main/kotlin/com/seugi/api/global/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/NiceSchoolService.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/info/SchoolInfoClient.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/info/SchoolInfoResponse.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/meal/SchoolMealClient.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/meal/SchoolMealResponse.kt
Labels: Feat

#219 Fix :: 워크스페이스 참가 승인 후 프로필이 안만들어지는 경우
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/ProfileAdapter.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepository.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustomImpl.kt
Labels: Fix

#221 Fix :: 워크스페이스 조회시 체크를 위한 함수를 공통함수로 수정 #220
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
  src/main/kotlin/com/seugi/api/global/exception/CustomExceptionHandler.kt
Labels: Fix

#223 Feat :: 워크스페이스에서의 내 권한 조회
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#224 Fix :: 워크스페이스 멤버 참가 승인 후 프로필 생성 안됨
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#228 Refactor :: JwtAuthenticationFilter 토큰 검증 로직
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/ErrorResponseSender.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtExceptionFilter.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/type/JwtErrorType.kt
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
  src/main/kotlin/com/seugi/api/global/exception/CommonErrorCode.kt
Labels: Fix, Refactor

#231 Fix :: 멤버 도메인 권한 인식 문제 & 필터 에러 응답 BaseResponse 사용
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/ErrorResponseSender.kt
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
  src/main/kotlin/com/seugi/api/global/response/BaseResponse.kt
Labels: Fix

#234 Feat :: 프로필 도메인 학번 추가
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/controller/EditSchoolIdNumController.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/request/EditSchIdNumRequest.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveProfileResponse.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveSchIdNumResponse.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/entity/ProfileEntity.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/mapper/ProfileMapper.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/Profile.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileSchClass.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileSchGrade.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileSchNumber.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/in/EditSchIdNumUseCase.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/in/RetrieveSchIdNumUseCase.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/EditSchIdNumService.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/RetrieveSchIdNumService.kt
Labels: Feat

#236 Hotfix :: 토큰 만료 시 401 반환
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
Labels: Fix

#237 Feat :: 시간표 확인 로직 #198
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableEntity.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableRepository.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/mapper/TimetableMapper.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/model/Timetable.kt
  src/main/kotlin/com/seugi/api/domain/timetable/exception/TimetableException.kt
  src/main/kotlin/com/seugi/api/domain/timetable/presentation/TimetableController.kt
  src/main/kotlin/com/seugi/api/domain/timetable/service/TimetableService.kt
  src/main/kotlin/com/seugi/api/domain/timetable/service/TimetableServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/entity/WorkspaceEntity.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/NiceSchoolService.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/timetable/SchoolTimetableClient.kt
  src/main/kotlin/com/seugi/api/global/infra/nice/school/timetable/SchoolTimetableResponse.kt
Labels: Feat

#239 Fix :: 시간표 삭제 기능 추가
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/timetable/domain/TimetableRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/timetable/service/TimetableServiceImpl.kt
Labels: Fix, Feat
