Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-03, with the labels that each got.

#3 Feature/chatting #1
  Dockerfile
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/chat/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/seugi/server/domain/chat/websocket/controller/StompChatController.kt
  src/main/kotlin/seugi/server/domain/chat/websocket/dto/ChatMessageDto.kt
Labels: Feat

#7 Feature :: 채팅 저장을 위한 기초 틀 작업
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Emoji.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Read.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/UnRead.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/status/ChatStatusEnum.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/joined/controller/JoinedController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/message/controller/MessageController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/controller/ChatRoomController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/dto/request/CreateRoomRequest.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/controller/StompChatController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
Labels: Feat

#6 Feature :: JWT + 구글 OAuth2 기능 추가
  .gitignore
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/member/adapter/in/controller/LoginMemberController.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/controller/RegisterMemberController.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/dto/LoginMemberDTO.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/dto/RegisterMemberDTO.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/MemberAdapter.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/repository/MemberRepository.kt
  src/main/kotlin/seugi/server/domain/member/application/model/Member.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberBirth.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberEmail.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberId.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberLoginId.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberName.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberPassword.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberProvider.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberProviderId.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberRole.kt
  src/main/kotlin/seugi/server/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/seugi/server/domain/member/port/in/LoginMemberUseCase.kt
  src/main/kotlin/seugi/server/domain/member/port/in/RegisterMemberUseCase.kt
  src/main/kotlin/seugi/server/domain/member/port/out/ExistMemberPort.kt
  src/main/kotlin/seugi/server/domain/member/port/out/LoadMemberPort.kt
  src/main/kotlin/seugi/server/domain/member/port/out/SaveMemberPort.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtInfo.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtProperties.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtUserDetails.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtUserDetailsService.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/seugi/server/global/auth/oauth/CustomOAuth2UserDetails.kt
  src/main/kotlin/seugi/server/global/auth/oauth/GoogleMemberInfo.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberInfo.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberService.kt
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2FailureHandler.kt
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2SuccessfulHandler.kt
  src/main/kotlin/seugi/server/global/config/SecurityConfig.kt
  src/main/kotlin/seugi/server/global/config/SpringConfig.kt
  src/main/kotlin/seugi/server/global/exception/CustomErrorCode.kt
  src/main/kotlin/seugi/server/global/exception/CustomException.kt
  src/main/kotlin/seugi/server/global/exception/CustomExceptionHandler.kt
  src/main/kotlin/seugi/server/global/response/BaseResponse.kt
Labels: Feat

#8 Hotfix :: FK키 부분 빠트리고 올렸네요;;; 죄송합니다~
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageEntity.kt
Labels: Fix

#9 Hotfix :: JWT 검증 로직 & CustomException & BaseResponse
  src/main/kotlin/seugi/server/domain/member/adapter/out/MemberAdapter.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/repository/MemberRepository.kt
  src/main/kotlin/seugi/server/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/seugi/server/domain/member/exception/MemberErrorCode.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/seugi/server/global/auth/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/seugi/server/global/common/Mapper.kt
  src/main/kotlin/seugi/server/global/exception/CustomErrorCode.kt
  src/main/kotlin/seugi/server/global/exception/CustomExceptionHandler.kt
  src/main/kotlin/seugi/server/global/response/BaseResponse.kt
Labels: Fix

#10 Feature/querydsl
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/member/port/out/ExistMemberPort.kt
  src/main/kotlin/seugi/server/global/config/QuerydslConfig.kt
Labels: Fix

#11 Feat :: Issues Template 생성
  .github/ISSUE_TEMPLATE/feat-issues-template.md
  .github/ISSUE_TEMPLATE/fix-issues-template.md
Labels: Etc

#18 Feature :: Member 도메인 Query문 QueryDSL 적용
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/member/adapter/out/repository/MemberRepository.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/repository/MemberRepositoryCustom.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/repository/MemberRepositoryCustomImpl.kt
  src/main/kotlin/seugi/server/global/response/BaseResponse.kt
Labels: Feat

#21 Hotfix :: OAuth2 핸들러 URI 발급 시 rest.base-url 기준으로 생성
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2FailureHandler.kt
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2SuccessfulHandler.kt
Labels: Fix
