Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-06, with the labels that each got.

#137 Fix :: 이메일 인증 리팩터링
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/member/ChatMemberServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Type.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/enums/type/EventType.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/member/controller/ChatMemberController.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/EmailAdapter.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/in/SendEmailController.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/in/VerifyEmailController.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/entity/CodeEntity.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/entity/TokenEntity.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/repository/TokenRepository.kt
  src/main/kotlin/com/seugi/api/domain/email/application/exception/EmailErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/ConfirmCodeService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/ConfirmTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/CreateCodeService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/CreateTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/RetrieveTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/SendEmailService.kt
  src/main/kotlin/com/seugi/api/domain/email/port/in/ConfirmCodeUseCase.kt
  src/main/kotlin/com/seugi/api/domain/email/port/in/ConfirmTokenUseCase.kt
  src/main/kotlin/com/seugi/api/domain/email/port/in/CreateCodeUseCase.kt
  src/main/kotlin/com/seugi/api/domain/email/port/in/CreateTokenUseCase.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/LoadCodePort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/LoadEmailPort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/LoadTokenPort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/SaveCodePort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/SaveEmailPort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/SaveTokenPort.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/dto/req/RegisterMemberRequest.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/RegisterMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
Labels: Fix

#138 Refactor :: 간단한 로직변경
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/mapper/JoinedMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/model/Joined.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/controller/GroupChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/controller/PersonalChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/controller/StompChatController.kt
Labels: Refactor

#140 Hotfix :: 워크스페이스 가입 시 프로필 생성
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/ProfileAdapter.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/Profile.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/in/CreateProfileUseCase.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/out/ExistProfilePort.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/CreateProfileService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#139 Feat :: 멤버 정보 수정 API
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/EditMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/dto/req/EditMemberRequest.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/Member.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/EditMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/EditMemberService.kt
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
Labels: Feat, First

#141 Fix :: Workspace, Message, ChatRoom 부분 사소한 수정사항
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/embeddable/MessageEmbed.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/MessageEventDto.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/CreateProfileService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix, Feat

#142 Build :: CI Test
  .github/workflows/gradle.yml
  src/main/kotlin/com/seugi/api/domain/profile/application/service/CreateProfileService.kt
Labels: Build

#144 Refactor :: 채팅룸 ID 형변환 수정
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/message/controller/MessageController.kt
Labels: Fix, Refactor

#145 Fix :: 메시지 관련 타입 변경 및 로깅 추가
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
Labels: Fix

#147 Fix :: 프로필 반환 시 검증을 위해 멤버 ID 반환
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveProfileResponse.kt
Labels: Fix

#151 Feature/#119&#150
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
Labels: Fix

#153 Refactor :: JWT 인증 필터 및 오류 타입 구조 개선
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/type/JwtErrorType.kt
Labels: Refactor

#154 Refactor :: JWT 인증 필터 로직 변경 및 오류 타입 추가
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/type/JwtErrorType.kt
Labels: Fix, Refactor

#155 Chore :: 귀찮은일 제거
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/model/Room.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/dto/response/RoomResponse.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
Labels: Fix

#158 Hotfix :: 소켓 연결 문제 해결
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
Labels: Fix, First

#159 Hotfix :: 소켓 연결문제 해결
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
Labels: Fix, First

#160 Feat :: 마지막 메시지 정보 채팅방 반환에 추가
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/dto/response/RoomResponse.kt
Labels: Feat

#162 Feat :: 채팅방에서 읽지 않은 메시지 개수 반환 추가
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/dto/response/RoomResponse.kt
Labels: Feat

#163 Fix :: 채팅방 안읽은 메시지 갯수 반환 #161
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
Labels: Fix

#165 Feat :: 워크스페이스 신청 대기 목록 불러오기 로직 #164
  src/main/kotlin/com/seugi/api/domain/workspace/domain/WorkspaceRepository.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#166 Feat :: 워크스페이스 전체 멤버 불러오기
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RefreshTokenController.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/value/MemberRefreshToken.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/response/WorkspaceMemberListResponse.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#168 Feat :: 워크스페이스 멤버 전체 조회 로직 작성
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/response/WorkspaceMemberChartResponse.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#171 Fix :: 회원가입 시 토큰 발급
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RegisterMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/RegisterMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
Labels: Fix, First

#173 Fix :: 프로필 반환 시 멤버 사진 추가
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveProfileResponse.kt
Labels: Fix

#175 Fix :: 프로필 반환 시 멤버 정보 포함
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveProfileResponse.kt
Labels: Feat

#177 조직도 반환 시 워크스페이스 어드민 + 중간 어드민 추가
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/response/WorkspaceMemberChartResponse.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#183 워크스페이스 전체 멤버 반환 시 admin, middleAdmin 세트에 추가
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#184 Refactor :: Workspace #181
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/member/ChatMemberServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/CreateCodeService.kt
  src/main/kotlin/com/seugi/api/domain/file/service/FileServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/EditMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RemoveMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RetrieveMemberService.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/EditProfileService.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/RetrieveProfileService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix, Refactor

#185 Feat :: 메시지 값이 삭제됬을시 빈값 반환 #120
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
Labels: Fix, Feat
