Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-05, with the labels that each got.

#82 이슈해결 (버그수정)
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/GroupChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/PersonalChatController.kt
  src/main/kotlin/com/seugi/api/domain/file/presentation/FileController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
Labels: Fix

#83 Workspace 사소한 이슈 수정
  src/main/kotlin/com/seugi/api/domain/workspace/exception/WorkspaceErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#84 Fix :: 맴버 추가시 저장 안되던 문제 수정
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix, First

#86 Feat :: 리프레시 토큰 발급 로직 작성
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RefreshTokenController.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/domain/member/port/in/RefreshTokenUseCase.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
Labels: Feat

#92 Refactor :: Message 도메인 리팩토링
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/embeddable/MessageEmbed.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
Labels: Fix

#93 Feat :: 테스트 토큰 발급기
  .gitignore
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/TestMemberController.kt
  src/main/kotlin/com/seugi/api/global/common/property/TestMemberProperty.kt
Labels: Feat

#97 Feat :: Cors 문제 해결
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
Labels: Fix

#98 Fix :: Workspace 지워진 방도 불러와지던 로직 수정
  src/main/kotlin/com/seugi/api/domain/workspace/domain/WorkspaceRepository.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#99 Fix :: Workspace 지워진 도 와지던 로직 수정
  src/main/kotlin/com/seugi/api/domain/workspace/domain/WorkspaceRepository.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#101 Feat :: 메시지 실시간 읽음 처리 로직 구현
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Type.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/info/RoomInfoEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/info/RoomInfoRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/entity/WorkspaceEntity.kt
Labels: Feat

#108 Fix :: 회원가입 시 birth 안받기 & CORS 해결
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/dto/OAuth2MemberDTO.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/dto/RegisterMemberDTO.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
Labels: Fix

#104 Message 도메인 기타작업
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/embeddable/MessageEmbed.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Type.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/joined/dto/response/GetMessageResponse.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/message/controller/MessageController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/controller/StompRabbitMQController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/MessageEventDto.kt
Labels: Feat

#117 Fix :: 방 생성, 나갈시 메시지값이 null이라 NPE 발생하던 문제 해결
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
Labels: Fix

#113 Feat :: 프로필 편집 & 불러오기
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/EditMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/LoginMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/OAuth2MemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RefreshTokenController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RegisterMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/TestMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/MemberAdapter.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/com/seugi/api/domain/member/application/exception/MemberErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/Member.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/EditMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/LoginMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/OAuth2MemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/RefreshTokenUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/RegisterMemberUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/out/ExistMemberPort.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/out/LoadMemberPort.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/out/SaveMemberPort.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/EditMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/controller/EditProfileController.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/controller/RetrieveProfileController.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/request/EditProfileRequest.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/in/response/RetrieveProfileResponse.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/ProfileAdapter.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/entity/ProfileEntity.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/mapper/ProfileMapper.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepository.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/profile/adapter/out/repository/ProfileRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/exception/ProfileErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/Profile.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileBelong.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileId.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileLocation.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileNick.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfilePhone.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileSpot.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileStatus.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileWire.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/model/value/ProfileWorkspaceId.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/in/EditProfileUseCase.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/in/RetrieveProfileUseCase.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/out/LoadProfilePort.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/port/out/SaveProfilePort.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/EditProfileService.kt
  src/main/kotlin/com/seugi/api/domain/profile/application/service/RetrieveProfileService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUserDetailsService.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
Labels: Feat, First

#90 Feat :: 리프레시 토큰 DB에 저장
  build.gradle.kts
  src/main/kotlin/com/seugi/api/domain/email/adapter/EmailAdapter.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/entity/CodeEntity.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/entity/TokenEntity.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/repository/CodeRepository.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/repository/EmailRepository.kt
  src/main/kotlin/com/seugi/api/domain/email/adapter/out/repository/TokenRepository.kt
  src/main/kotlin/com/seugi/api/domain/email/application/exception/EmailErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/ConfirmTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/CreateTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/RetrieveTokenService.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/LoadEmailPort.kt
  src/main/kotlin/com/seugi/api/domain/email/port/out/LoadTokenPort.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/RefreshTokenController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/MemberAdapter.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberTokenEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/repository/MemberRepository.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/repository/MemberRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/repository/MemberRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/repository/MemberTokenRepository.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/value/MemberRefreshToken.kt
  src/main/kotlin/com/seugi/api/domain/member/application/port/in/RefreshTokenUseCase.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/com/seugi/api/global/config/RedisConfig.kt
Labels: Feat, First

#127 Fix :: @GetAuthenticatedId SPeL -1 Long 지정
  src/main/kotlin/com/seugi/api/global/common/annotation/GetAuthenticatedId.kt
Labels: Fix

#129 Fix :: 채팅 단건 조회시 예외처리 추가 #123
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
Labels: Fix

#131 Fix :: 멤버 토큰 저장 로직 삭제
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberTokenEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/repository/MemberTokenRepository.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RefreshTokenService.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/JwtUtils.kt
  src/main/kotlin/com/seugi/api/global/auth/jwt/exception/JwtErrorCode.kt
Labels: Fix
