Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-04, with the labels that each got.

#26 Create test.yml
  .github/test.yml
Labels: Build

#27 Create gradle.yml
  .github/workflows/gradle.yml
Labels: Fix, Build

#25 Feat :: saveChatting
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Emoji.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Read.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/UnRead.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/mapper/JoinedMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/model/Joined.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomRepositoryCustom.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomRepositoryCustomImpl.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/model/Room.kt
  src/main/kotlin/seugi/server/domain/chat/exception/ChatErrorCode.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/controller/ChatRoomController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/dto/request/CreateRoomRequest.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtUserDetails.kt
  src/main/kotlin/seugi/server/global/common/annotation/GetAuthenticatedId.kt
  src/main/kotlin/seugi/server/global/config/RedisConfig.kt
Labels: Feat

#24 Hotfix :: 정상적인 토큰으로 없는 유저 조회 시 null 익셉션 처리
  src/main/kotlin/seugi/server/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/seugi/server/global/auth/jwt/exception/JwtErrorCode.kt
Labels: Fix

#30 Feat :: 채팅 저장 로직 완료
  .github/workflows/gradle.yml
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Read.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/UnRead.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/controller/StompChatController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
  src/main/kotlin/seugi/server/global/config/SecurityConfig.kt
Labels: Feat

#37 Feat :: 이메일 인증 로직 구현
  .gitignore
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/email/adapter/EmailAdapter.kt
  src/main/kotlin/seugi/server/domain/email/adapter/in/SendEmailController.kt
  src/main/kotlin/seugi/server/domain/email/adapter/in/VerifyEmailController.kt
  src/main/kotlin/seugi/server/domain/email/adapter/out/repository/EmailRepository.kt
  src/main/kotlin/seugi/server/domain/email/application/exception/EmailErrorCode.kt
  src/main/kotlin/seugi/server/domain/email/application/service/ConfirmTokenService.kt
  src/main/kotlin/seugi/server/domain/email/application/service/CreateTokenService.kt
  src/main/kotlin/seugi/server/domain/email/application/service/RetrieveTokenService.kt
  src/main/kotlin/seugi/server/domain/email/application/service/SendEmailService.kt
  src/main/kotlin/seugi/server/domain/email/port/in/ConfirmTokenUseCase.kt
  src/main/kotlin/seugi/server/domain/email/port/in/CreateTokenUseCase.kt
  src/main/kotlin/seugi/server/domain/email/port/in/RetrieveTokenUseCase.kt
  src/main/kotlin/seugi/server/domain/email/port/in/SendEmailUseCase.kt
  src/main/kotlin/seugi/server/domain/email/port/out/LoadEmailPort.kt
  src/main/kotlin/seugi/server/domain/email/port/out/LoadTokenPort.kt
  src/main/kotlin/seugi/server/domain/email/port/out/SaveEmailPort.kt
  src/main/kotlin/seugi/server/domain/email/port/out/SaveTokenPort.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/dto/RegisterMemberDTO.kt
  src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/seugi/server/global/config/SecurityConfig.kt
Labels: Feat

#34 Feature/getChatting
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomService.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/Emoji.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/embeddable/MessageEmbed.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/seugi/server/domain/chat/domain/chat/model/Type.kt
  src/main/kotlin/seugi/server/domain/chat/domain/enums/status/ChatStatusEnum.kt
  src/main/kotlin/seugi/server/domain/chat/domain/enums/type/RoomType.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/JoinedRepository.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/mapper/JoinedMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/joined/model/Joined.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/ChatRoomEntity.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/seugi/server/domain/chat/domain/room/model/Room.kt
  src/main/kotlin/seugi/server/domain/chat/domain/status/ChatStatusEnum.kt
  src/main/kotlin/seugi/server/domain/chat/exception/ChatErrorCode.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/joined/controller/JoinedController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/joined/dto/request/AddJoinedRequest.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/joined/dto/request/OutJoinedRequest.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/message/controller/MessageController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/controller/GroupChatController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/controller/PersonalChatController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/room/dto/request/CreateRoomRequest.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/controller/StompChatController.kt
  src/main/kotlin/seugi/server/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
Labels: Feat

#39 Feat :: 멤버에 프로필 속성 추가
  src/main/kotlin/seugi/server/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/seugi/server/domain/member/application/model/value/MemberProfile.kt
Labels: Feat

#41 Hotfix :: DockerFile 수정
  Dockerfile
Labels: Fix

#42 Feat :: OAuth2 수동 처리 로직 구현
  .gitignore
  build.gradle.kts
  src/main/kotlin/seugi/server/domain/member/adapter/in/controller/OAuth2MemberController.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/MemberAdapter.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/seugi/server/domain/member/application/model/Member.kt
  src/main/kotlin/seugi/server/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/seugi/server/domain/member/port/in/OAuth2MemberUseCase.kt
  src/main/kotlin/seugi/server/global/auth/oauth/CustomOAuth2UserDetails.kt
  src/main/kotlin/seugi/server/global/auth/oauth/GoogleMemberInfo.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberInfo.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberService.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2Properties.kt
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2FailureHandler.kt
  src/main/kotlin/seugi/server/global/auth/oauth/handler/OAuth2SuccessfulHandler.kt
  src/main/kotlin/seugi/server/global/config/SecurityConfig.kt
  src/main/kotlin/seugi/server/global/config/SpringConfig.kt
Labels: Feat

#43 Build :: Dockerfile Fix
  Dockerfile
Labels: Fix, Build

#44 Build :: Dockerfile Fix
  Dockerfile
Labels: Fix, Build

#45 Build :: Dockerfile Fix
  Dockerfile
Labels: Fix, Build

#46 Build :: Dockerfile Fix 찐막
  Dockerfile
Labels: Fix, Build

#51 Fix :: BaseResponse Status 필드 타입 수정
  src/main/kotlin/seugi/server/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/seugi/server/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/seugi/server/domain/email/application/service/CreateTokenService.kt
  src/main/kotlin/seugi/server/domain/email/application/service/RetrieveTokenService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/LoginMemberService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/seugi/server/global/auth/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/seugi/server/global/auth/oauth/OAuth2Properties.kt
  src/main/kotlin/seugi/server/global/exception/CustomExceptionHandler.kt
  src/main/kotlin/seugi/server/global/response/BaseResponse.kt
Labels: Fix

#53 Feat :: OAuth2 최초 가입 시 추가정보 받기
  src/main/kotlin/seugi/server/domain/email/application/service/CreateTokenService.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/controller/OAuth2MemberController.kt
  src/main/kotlin/seugi/server/domain/member/adapter/in/dto/OAuth2MemberDTO.kt
  src/main/kotlin/seugi/server/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/seugi/server/domain/member/application/exception/MemberErrorCode.kt
  src/main/kotlin/seugi/server/domain/member/application/model/Member.kt
  src/main/kotlin/seugi/server/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/seugi/server/domain/member/port/in/OAuth2MemberUseCase.kt
Labels: Feat

#56 Feat :: 방장 위임 로직 추가
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/JoinedEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/exception/ChatErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/joined/controller/JoinedController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/joined/dto/request/TossMasterRequest.kt
Labels: Fix, Feat

#57 Build :: 폴더 수정에 따른 도커파일 수정
  Dockerfile
Labels: Fix, Build

#58 Build :: 오류나서 걍 하드코딩 함
  Dockerfile
Labels: Fix, Build

#60 S3 세팅
  build.gradle.kts
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/global/auth/oauth/S3Properties.kt
  src/main/kotlin/com/seugi/api/global/infra/S3.kt
Labels: Feat

#63 Fix/S3 Uploader
  src/main/kotlin/com/seugi/api/global/infra/aws/s3/exception/S3Exception.kt
  src/main/kotlin/com/seugi/api/global/infra/aws/s3/service/S3.kt
  src/main/kotlin/com/seugi/api/global/infra/aws/s3/type/FileType.kt
Labels: Fix, Feat

#65 Feature/#62
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/mapper/RoomMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/model/Room.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/dto/request/CreateRoomRequest.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
  src/main/kotlin/com/seugi/api/domain/file/exception/FileErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/file/presentation/FileController.kt
  src/main/kotlin/com/seugi/api/domain/file/service/FileService.kt
  src/main/kotlin/com/seugi/api/domain/file/service/FileServiceImpl.kt
Labels: Feat, First

#66 Feat :: 멤버 프로필 사진 편집 기능 추가
  .gitignore
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/EditMemberController.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/mapper/MemberMapper.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/Member.kt
  src/main/kotlin/com/seugi/api/domain/member/application/model/value/MemberPicture.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/EditMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/OAuth2MemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/application/service/RegisterMemberService.kt
  src/main/kotlin/com/seugi/api/domain/member/port/in/EditMemberUseCase.kt
Labels: Feat

#67 Feat :: S3 채팅 도메인 완료
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
Labels: Feat

#71 Feat :: 모니터링 시스템 (Spring Actuator)
  build.gradle.kts
  src/main/kotlin/com/seugi/api/global/config/ActuatorHttpExchangesConfiguration.kt
  src/main/kotlin/com/seugi/api/global/config/SecurityConfig.kt
Labels: Feat, First

#73 Feature/#72
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/JoinedEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/JoinedRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/mapper/JoinedMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/joined/model/Joined.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/GroupChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/PersonalChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/dto/request/CreateRoomRequest.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
Labels: Fix, Feat, First

#75 채팅방 검색 로직 구현
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/room/ChatRoomRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/GroupChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/controller/PersonalChatController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/room/dto/request/SearchRoomRequest.kt
Labels: Feat

#79 Fix :: Member 도메인 Mapper 도메인 모델 내 id가 null일 때 강제 참조로 인해 NPE가 발생하는 문제 해결
  .gitignore
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/entity/MemberEntity.kt
  src/main/kotlin/com/seugi/api/domain/member/adapter/out/mapper/MemberMapper.kt
Labels: Fix

#80 Feature/#77
  src/main/kotlin/com/seugi/api/domain/chat/application/service/joined/JoinedServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageEntity.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/MessageRepository.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Message.kt
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/model/Type.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/controller/StompRabbitMQController.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/dto/ChatMessageDto.kt
  src/main/kotlin/com/seugi/api/domain/email/application/service/SendEmailService.kt
Labels: Fix, Feat, First
