Repository apeun-gidaechi/seugi-server, pull requests merged in 2024-07, with the labels that each got.

#187 Fix :: ChatRead And RoomResponse
  src/main/kotlin/com/seugi/api/domain/chat/domain/chat/mapper/MessageMapper.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/room/dto/response/RoomResponse.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/websocket/config/StompWebSocketConfig.kt
Labels: Fix

#189 Feature :: 공지 로직 구성 #186
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeEntity.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepository.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/mapper/NoticeMapper.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/model/Notice.kt
  src/main/kotlin/com/seugi/api/domain/notice/exception/NoticeErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/controller/NoticeController.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/CreateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/UpdateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/response/NoticeResponse.kt
  src/main/kotlin/com/seugi/api/domain/notice/service/NoticeService.kt
  src/main/kotlin/com/seugi/api/domain/notice/service/NoticeServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#191 Fix :: 공지에 사소한 문제 해결
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeEntity.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/controller/NoticeController.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/CreateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/UpdateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/service/NoticeServiceImpl.kt
Labels: Fix, First

#194 Fix :: 워크스페이스 단건조회, 오타 수정
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageService.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/message/MessageServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/domain/mapper/WorkspaceMapper.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/response/WorkspaceInfoResponse.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/response/WorkspaceResponse.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix

#195 Fix :: SearchWorkspace
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix, First

#196 Fix :: Get 요청시 경로가 같아 상위 로직이 실행되던 문제 해결
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
Labels: Fix, First

#197 Refactor :: convention
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepository.kt
  src/main/kotlin/com/seugi/api/domain/notice/domain/NoticeRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/CreateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/presentation/dto/request/UpdateNoticeRequest.kt
  src/main/kotlin/com/seugi/api/domain/notice/service/NoticeService.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationEntity.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepository.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/mapper/NotificationMapper.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/model/Notification.kt
  src/main/kotlin/com/seugi/api/domain/notification/exception/NotificationErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/controller/NotificationController.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/dto/request/CreateNotificationRequest.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/dto/request/UpdateNotificationRequest.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/dto/response/NotificationResponse.kt
  src/main/kotlin/com/seugi/api/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/seugi/api/domain/notification/service/NotificationServiceImpl.kt
Labels: Refactor

#201 Refactor :: 담당 도메인 전반적 리팩토링
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/member/ChatMemberServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/presentation/chat/member/dto/request/ChatMemberEventRequest.kt
  src/main/kotlin/com/seugi/api/domain/notification/service/NotificationServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/exception/WorkspaceErrorCode.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: First, Refactor

#210 Feature :: Workspace 가입 취소 로직
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/controller/WorkspaceController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/presentation/dto/request/WaitSetWorkspaceMemberRequest.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceService.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Fix, Feat

#211 Feature :: 공지 이모지 로직 및 페이징 처리
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/member/ChatMemberServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/chat/application/service/chat/room/ChatRoomServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationEntity.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepository.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepositoryCustom.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/NotificationRepositoryCustomImpl.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/embeddable/NotificationEmoji.kt
  src/main/kotlin/com/seugi/api/domain/notification/domain/model/Notification.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/controller/NotificationController.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/dto/request/NotificationEmojiRequest.kt
  src/main/kotlin/com/seugi/api/domain/notification/presentation/dto/response/NotificationResponse.kt
  src/main/kotlin/com/seugi/api/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/seugi/api/domain/notification/service/NotificationServiceImpl.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
Labels: Feat

#212 Fix :: 워크스페이스 생성자의 프로필이 생성되지 않음
  src/main/kotlin/com/seugi/api/domain/member/adapter/in/controller/TestMemberController.kt
  src/main/kotlin/com/seugi/api/domain/workspace/service/WorkspaceServiceImpl.kt
  src/main/kotlin/com/seugi/api/global/common/property/TestMemberProperty.kt
Labels: Fix

#214 Feature :: local, prod 개발 환경 분리 및 디스코드 로깅
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  build.gradle.kts
  src/main/kotlin/com/seugi/api/SeugiServerApplication.kt
  src/main/kotlin/com/seugi/api/global/exception/CustomExceptionHandler.kt
  src/main/kotlin/com/seugi/api/global/infra/discord/webhook/DiscordClient.kt
  src/main/kotlin/com/seugi/api/global/infra/discord/webhook/DiscordErrorSendService.kt
  src/main/kotlin/com/seugi/api/global/infra/discord/webhook/DiscordMessage.kt
  src/main/resources/application.yml
Labels: Feat, Build
